Repository KoreaMoney/eum, pull requests merged in 2023-03, with the labels that each got.

#98 feat/auth-loading시간 줄이기, 기타 버그 수정
  src/components/comment/CommentsList.tsx
  src/components/home/image-data.ts
  src/components/mypage/PointModal.tsx
  src/components/mypage/Profile.tsx
  src/pages/CategoryPage.tsx
  src/pages/Detail.tsx
  src/pages/Home.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/Transaction.tsx
  src/router/Router.tsx
  src/styles/basicIMG.png
  src/styles/basicIMG.webp
  src/styles/styledComponent/transaction.ts
Labels: bug, enhancement

#99 feat : 내가 쓴 글 검색량과 리뷰 글 수량 차트 구성
  package.json
  src/components/mypage/Chart.tsx
  src/components/mypage/Profile.tsx
  src/index.tsx
  src/pages/MyPage.tsx
  src/styles/styledComponent/myPage.ts
Labels: enhancement

#100 fix : chart 기간별 분류 진행
  src/components/mypage/Chart.tsx
  src/pages/MyPage.tsx
Labels: enhancement

#101 feat : 판매자 정보 따로 분리
  src/components/detail/SellerInfo.tsx
  src/components/mypage/Chart.tsx
  src/pages/Detail.tsx
  src/pages/WritePage.tsx
  src/styles/styledComponent/detail.ts
Labels: enhancement

#102 feat(MyPage): 마이페이지 관심목록과 판매,구매 내역과 후기관리를 나타냅니다.
  src/api.ts
  src/components/mypage/PointHistoryList.tsx
  src/pages/MyPage.tsx
Labels: enhancement

#103 fix:comments,transaction
  src/api.ts
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentsList.tsx
  src/pages/Detail.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/Transaction.tsx
  src/types.d.ts
Labels: enhancement

#104 feat(MyPage): 마이페이지 일부 기능을 컴퍼넌트화 합니다.
  src/components/mypage/Profile.tsx
  src/components/mypage/UserTime.tsx
  src/pages/MyPage.tsx
Labels: enhancement

#105 Feat/new theme
  src/pages/Home.tsx
  src/pages/Transaction.tsx
  src/pages/WritePage.tsx
  src/styles/styled.d.ts
  src/styles/styledComponent/auth.ts
  src/styles/styledComponent/category.ts
  src/styles/styledComponent/detail.ts
  src/styles/styledComponent/editPage.ts
  src/styles/styledComponent/home.ts
  src/styles/styledComponent/transaction.ts
  src/styles/styledComponent/writeEdit.ts
  src/styles/theme.ts
Labels: enhancement

#106 fix : theme
  src/components/auth/FindPW.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentsList.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/mypage/Profile.tsx
Labels: bug

#107 feat(profile): 프로필 사진이 업로드되면 프로필 배경을 삭제합니다.
  src/components/mypage/Profile.tsx
Labels: enhancement

#108 fix(MyPage): 닉네임 컴포넌트를 분리하고 주석 정리와 안쓰는 코드를 삭제합니다.
  src/components/mypage/ProfileImg.tsx
  src/components/mypage/UserName.tsx
  src/pages/MyPage.tsx
Labels: enhancement

#109 fix:transaction
  src/atom.ts
  src/pages/Detail.tsx
  src/pages/Transaction.tsx
Labels: enhancement

#110 ui(MyPage): 마이페이지의 UI를 수정합니다.
  public/index.html
  src/components/modal/CustomModal.tsx
  src/components/mypage/PointHistoryList.tsx
  src/components/mypage/PointModal.tsx
  src/components/mypage/ProfileImg.tsx
  src/components/mypage/UserName.tsx
  src/components/mypage/UserTime.tsx
  src/pages/MyPage.tsx
  src/styles/styledComponent/myPage.ts
Labels: enhancement

#111 ui(Profile): Profile 관련 UI를 수정합니다.
  src/components/mypage/PointHistoryList.tsx
  src/components/mypage/PointModal.tsx
  src/components/mypage/ProfileImg.tsx
  src/components/mypage/UserTime.tsx
  src/pages/MyPage.tsx
  src/styles/styledComponent/myPage.ts
Labels: enhancement

#112 ui(MyPage): 마이페이지 Nav UI와 Profile Nav UI를 수정합니다.
  public/index.html
  src/components/mypage/PointHistoryList.tsx
  src/components/mypage/UserTime.tsx
  src/pages/MyPage.tsx
  src/styles/styledComponent/myPage.ts
Labels: enhancement

#113 Feat/home UI
  package.json
  src/components/etc/SearchInput.tsx
  src/components/home/Banner.tsx
  src/components/home/NextArrow.tsx
  src/components/home/PrevArrow.tsx
  src/components/home/image-data.ts
  src/components/home/index.tsx
  src/components/home/variants.ts
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/mypage/Chart.tsx
  src/pages/Home.tsx
  src/pages/SignUp.tsx
  src/styles/GlobalStyle.tsx
  src/styles/styledComponent/home.ts
Labels: enhancement

#114 fix:category+detail
  public/index.html
  src/atom.ts
  src/components/categoryHome/CategoryIntros.tsx
  src/components/categoryHome/Post.tsx
  src/components/categoryHome/SortPosts.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentsList.tsx
  src/components/detail/SellerInfo.tsx
  src/pages/CategoryPage.tsx
  src/pages/Detail.tsx
  src/pages/SignUp.tsx
  src/styles/GlobalStyle.tsx
  src/styles/styledComponent/category.ts
  src/styles/styledComponent/detail.ts
  src/types.d.ts
Labels: enhancement

#115 ui(MyPage): 마이페이지 전체 UI와 일부 기능을 수정합니다.
  public/assets/like.png
  src/pages/MyPage.tsx
  src/styles/styledComponent/myPage.ts
Labels: enhancement

#116 Fix/home UI
  src/components/etc/SearchInput.tsx
  src/components/home/Banner.tsx
  src/components/layout/Header.tsx
  src/pages/Detail.tsx
  src/styles/styledComponent/detail.ts
Labels: bug

#117 fix : theme 색상 변경
  package.json
  src/components/comment/CommentsList.tsx
  src/components/etc/Loader.tsx
  src/components/etc/SearchInput.tsx
  src/components/home/Banner.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/mypage/Chart.tsx
  src/components/mypage/PointHistoryList.tsx
  src/components/mypage/PointModal.tsx
  src/components/mypage/ProfileImg.tsx
  src/components/mypage/UserTime.tsx
  src/pages/CategoryPage.tsx
  src/pages/Detail.tsx
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/pages/Transaction.tsx
  src/styles/styled.d.ts
  src/styles/styledComponent/category.ts
  src/styles/styledComponent/detail.ts
  src/styles/styledComponent/home.ts
  src/styles/styledComponent/myPage.ts
  src/styles/styledComponent/transaction.ts
  src/styles/theme.ts
Labels: enhancement

#118 UI/detail,edit,tranjaction,write
  src/components/comment/CommentsList.tsx
  src/components/detail/SellerInfo.tsx
  src/pages/Detail.tsx
  src/pages/EditPage.tsx
  src/pages/Transaction.tsx
  src/pages/WritePage.tsx
  src/router/Router.tsx
  src/styles/camera.png
  src/styles/deleteBt.png
  src/styles/quill.custom.css
  src/styles/styledComponent/detail.ts
  src/styles/styledComponent/transaction.ts
  src/styles/styledComponent/writeEdit.ts
Labels: enhancement

#119 ui(MyPage): 기본이미지를 assets에 추가합니다 MyPage UI를 수정합니다
  public/assets/basicIMG.jpg
  src/pages/MyPage.tsx
  src/styles/styledComponent/myPage.ts
Labels: enhancement

#120 UI/loading
  src/api.ts
  src/components/categoryHome/SortPosts.tsx
  src/components/comment/CommentsList.tsx
  src/components/detail/SellerInfo.tsx
  src/pages/CategoryPage.tsx
  src/pages/Detail.tsx
  src/pages/EditPage.tsx
  src/pages/WritePage.tsx
  src/styles/styledComponent/category.ts
  src/styles/styledComponent/detail.ts
  src/styles/styledComponent/transaction.ts
  src/styles/styledComponent/writeEdit.ts
Labels: enhancement

#122 Feat/badge
  .env
  src/pages/Detail.tsx
  src/pages/MyPage.tsx
  src/pages/ReviewPage.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/Transaction.tsx
  src/router/Router.tsx
  src/types.d.ts
Labels: enhancement

#123 Fix/header
  src/components/categoryHome/Post.tsx
  src/components/etc/SearchInput.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/modal/CustomAlert.ts
  src/pages/CategoryPage.tsx
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/pages/WritePage.tsx
  src/styles/styledComponent/category.ts
  src/styles/styledComponent/home.ts
  src/styles/styledComponent/writeEdit.ts
Labels: bug, enhancement

#124 fix/all:마이페이지하고 디테일 수정..
  src/pages/Detail.tsx
  src/pages/MyPage.tsx
  src/pages/Transaction.tsx
  src/styles/styledComponent/detail.ts
  src/styles/styledComponent/myPage.ts
  src/types.d.ts
Labels: enhancement

#125 ui(MyPage): 회원관리 UI를 수정합니다.
  src/components/mypage/PointModal.tsx
  src/components/mypage/ProfileImg.tsx
  src/pages/MyPage.tsx
  src/styles/styledComponent/myPage.ts
Labels: enhancement

#126 fix(UIText): UI와 text를 변경합니다.
  src/components/categoryHome/Post.tsx
  src/pages/Detail.tsx
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/pages/Transaction.tsx
  src/styles/styledComponent/myPage.ts
Labels: enhancement

#127 feat(Point): 포인트 내역 페이지를 수정합니다
  public/assets/Vector.png
  src/components/mypage/PointHistoryList.tsx
  src/components/mypage/PointModal.tsx
  src/pages/MyPage.tsx
  src/styles/styledComponent/myPage.ts
Labels: enhancement

#128 ui : auth-ui를 작업이 되었습니다.
  src/components/error/Error404.tsx
  src/components/error/index.tsx
  src/components/layout/Header.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/router/Router.tsx
  src/styles/styledComponent/auth.ts
Labels: enhancement

#129 ui : 404error, find pw
  src/components/auth/FindPW.tsx
  src/components/error/Error404.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/types.d.ts
Labels: enhancement

#130 Feat,UI/mypage badge
  src/atom.ts
  src/components/mypage/UserName.tsx
  src/components/mypage/UserTime.tsx
  src/components/mypage/member/Badge.tsx
  src/components/mypage/member/MemberInfo.tsx
  src/components/mypage/member/ProfileImg.tsx
  src/components/mypage/member/Terms.tsx
  src/components/mypage/member/UserName.tsx
  src/pages/MyPage.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/styles/badge/choice/c_cheap.webp
  src/styles/badge/choice/c_donation.webp
  src/styles/badge/choice/c_fast.webp
  src/styles/badge/choice/c_manner.webp
  src/styles/badge/choice/c_service.webp
  src/styles/badge/choice/c_time.webp
  src/styles/badge/lock/lock_cheap.webp
  src/styles/badge/lock/lock_donation.webp
  src/styles/badge/lock/lock_fast.webp
  src/styles/badge/lock/lock_manner.webp
  src/styles/badge/lock/lock_service.webp
  src/styles/badge/lock/lock_time.webp
  src/styles/badge/notChoice/nc_cheap.webp
  src/styles/badge/notChoice/nc_donation.webp
  src/styles/badge/notChoice/nc_fast.webp
  src/styles/badge/notChoice/nc_manner.webp
  src/styles/badge/notChoice/nc_service.webp
  src/styles/badge/notChoice/nc_time.webp
  src/styles/basicIMG.webp
  src/styles/styledComponent/myPage.ts
  src/types.d.ts
Labels: enhancement

#131 feat : 일부 알럿창이 추가 되었습니다.
  src/components/error/Error404.tsx
  src/components/mypage/member/MemberInfo.tsx
  src/pages/Detail.tsx
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/pages/Transaction.tsx
  src/styles/styledComponent/detail.ts
Labels: enhancement

#132 hotfix : banner
  src/components/home/Banner.tsx
Labels: bug, enhancement

#134 ui/review:리뷰페이지 ui 완성
  src/pages/ReviewPage.tsx
  src/styles/badge/notChoice/nc_cheap.webp
  src/styles/badge/notChoice/nc_service.webp
Labels: enhancement

#133 feat(Mypage): 마이페이지에서 Post를 클릭하면 해당 페이지로 이동합니다.
  src/components/mypage/PointHistoryList.tsx
  src/components/mypage/PointModal.tsx
  src/pages/MyPage.tsx
  src/styles/styledComponent/myPage.ts
Labels: enhancement

#135 fix/etc:
  src/components/comment/CommentsList.tsx
  src/components/detail/SellerInfo.tsx
  src/components/mypage/member/Badge.tsx
  src/pages/Detail.tsx
  src/pages/ReviewPage.tsx
  src/styles/badge/basicLock.webp
  src/styles/styledComponent/detail.ts
Labels: enhancement

#136 Fix/UI UI others
  src/components/auth/FindPW.tsx
  src/components/error/Error404.tsx
  src/components/etc/SearchInput.tsx
  src/components/home/Banner.tsx
  src/components/home/NextArrow.tsx
  src/components/home/PrevArrow.tsx
  src/components/layout/Header.tsx
  src/components/mypage/Chart.tsx
  src/hooks/Infinite.tsx
  src/pages/Home.tsx
  src/pages/ReviewPage.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/Transaction.tsx
  src/styles/styledComponent/detail.ts
Labels: enhancement

#137 fix: 후기 댓글이 제대로 나오지 않던 현상 수정
  src/pages/ReviewPage.tsx
Labels: enhancement

#138 후기 뱃지 이미지와 데이터가 일치하지 않던 UI 문제 해결
  src/pages/ReviewPage.tsx
Labels: enhancement

#139 Fix/other
  src/components/home/Banner.tsx
  src/components/layout/Footer.tsx
  src/components/mypage/member/ProfileImg.tsx
  src/pages/Detail.tsx
  src/styles/styledComponent/detail.ts
  src/styles/styledComponent/writeEdit.ts
Labels: enhancement

#140 onsaleposts 데이터에 buyernickname추가
  src/pages/Detail.tsx
  src/pages/Transaction.tsx
  src/types.d.ts
Labels: enhancement

#143 feat,ui/onSaleModal: 디테일페이지에서 판매자가 구매자 명단확인 및 onsalepost로 갈 수 있는 모달 완성
  src/atom.ts
  src/components/modal/CustomModal.tsx
  src/components/modal/Custom사용법.txt
  src/components/transaction/BuyerModal.tsx
  src/pages/Detail.tsx
  src/styles/GlobalStyle.tsx
Labels: enhancement

#145 Fix/home UI size
  src/components/error/Error404.tsx
  src/components/etc/MoveTop.tsx
  src/components/home/Banner.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Layout.tsx
  src/components/mypage/member/UserName.tsx
  src/pages/Home.tsx
  src/pages/Transaction.tsx
Labels: enhancement

#146 fix(mypage): 포인트내역이 입, 출금이 반대로 표시되던 현상을 수정합니다.
  src/components/mypage/PointHistoryList.tsx
Labels: enhancement

#147 UI,feat/kakaomodal
  src/atom.ts
  src/components/detail/BuyerInfo.tsx
  src/components/detail/SellerInfo.tsx
  src/components/modal/BuyerModal.tsx
  src/components/modal/CustomModal.tsx
  src/components/modal/Custom사용법.txt
  src/components/modal/KakaoModal.tsx
  src/components/mypage/member/MemberInfo.tsx
  src/pages/Detail.tsx
  src/pages/SignIn.tsx
  src/pages/Transaction.tsx
Labels: enhancement

#149 Fix/bug
  src/components/auth/FindPW.tsx
  src/components/etc/MoveTop.tsx
  src/components/home/Banner.tsx
  src/components/modal/KakaoModal.tsx
  src/pages/Home.tsx
  src/pages/ReviewPage.tsx
  src/pages/SignUp.tsx
  src/pages/Transaction.tsx
Labels: bug

#150 fix(mypage): 리스트가 중복해서 뜨던 현상을 수정합니다.
  src/pages/MyPage.tsx
Labels: enhancement

#153 Fix/mypage
  src/components/detail/SellerInfo.tsx
  src/components/modal/KakaoModal.tsx
  src/pages/MyPage.tsx
Labels: bug

#154 fix/mypage:회원탈퇴 시 글리치에서도 유저정보 삭제되게 변경
  src/pages/MyPage.tsx
  src/pages/Transaction.tsx
Labels: enhancement

#155 Fix/mypage
  src/components/modal/KakaoModal.tsx
  src/pages/Detail.tsx
Labels: enhancement

#156 Fix/point
  src/components/mypage/PointModal.tsx
  src/styles/styledComponent/myPage.ts
Labels: bug

#157 ui(buyermodal): 모달창 종료버튼을 생성합니다.
  src/components/modal/BuyerModal.tsx
Labels: enhancement

#158 Feat/refactory
  src/components/categoryHome/CategoryIntros.tsx
  src/components/categoryHome/Post.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentsList.tsx
  src/components/detail/BuyerInfo.tsx
  src/components/detail/SellerInfo.tsx
  src/components/etc/SearchInput.tsx
  src/components/home/Banner.tsx
  src/components/modal/BuyerModal.tsx
  src/components/modal/KakaoModal.tsx
  src/components/mypage/Chart.tsx
  src/components/mypage/PointHistoryList.tsx
  src/components/mypage/PointModal.tsx
  src/components/mypage/member/Badge.tsx
  src/components/mypage/member/MemberInfo.tsx
  src/components/mypage/member/ProfileImg.tsx
  src/components/mypage/member/Terms.tsx
  src/components/mypage/member/UserName.tsx
  src/pages/CategoryPage.tsx
  src/pages/Detail.tsx
  src/pages/EditPage.tsx
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/pages/ReviewPage.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/Transaction.tsx
  src/pages/WritePage.tsx
  src/styles/GlobalStyle.tsx
  src/styles/styledComponent/detail.ts
  src/styles/styledComponent/reviewPage.ts
Labels: enhancement

#160 hotfix : dev수정
  src/components/mypage/PointHistoryList.tsx
  src/components/mypage/PointModal.tsx
  src/pages/Detail.tsx
  src/pages/SignIn.tsx
  src/pages/Transaction.tsx
  src/pages/WritePage.tsx
Labels: bug

#163 Fix/edit
  src/pages/CategoryPage.tsx
  src/pages/Detail.tsx
  src/pages/EditPage.tsx
Labels: enhancement

#164 fix/writePage: 사진 올리고 삭제 후 파일선택 창에서 닫기를 누르면 콘솔 에러나던부분 수정
  src/components/mypage/member/ProfileImg.tsx
  src/pages/WritePage.tsx
Labels: enhancement

#165 fix(mypage): 찜 목록을 보여줍니다.
  src/api.ts
  src/pages/MyPage.tsx
Labels: bug

#166 Feat/dev main과 dev 버전 최신화
  public/favicon.ico
  src/api.ts
  src/components/mypage/member/ProfileImg.tsx
  src/pages/CategoryPage.tsx
  src/pages/Detail.tsx
  src/pages/EditPage.tsx
  src/pages/MyPage.tsx
  src/pages/WritePage.tsx
Labels: enhancement

#167 hotfix : 회원탈퇴
  src/pages/MyPage.tsx
Labels: enhancement

#168 Dev
  src/pages/MyPage.tsx
Labels: bug

#169 Fix/little others
  src/components/etc/Loader.tsx
  src/components/etc/MoveTop.tsx
  src/components/etc/SearchInput.tsx
  src/components/home/Banner.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/modal/BuyerModal.tsx
  src/components/modal/CustomModal.tsx
  src/components/modal/KakaoModal.tsx
  src/pages/Home.tsx
  src/router/Router.tsx
  src/styles/GlobalStyle.tsx
  src/styles/styledComponent/detail.ts
  src/styles/styledComponent/writeEdit.ts
Labels: bug

#170 feat,ui/userProfilePage: 유저 프로필페이지 UI,모든기능 완성, 프로필사진에 onClick으로 연결해놨습니다.
  package.json
  src/api.ts
  src/atom.ts
  src/components/detail/BuyerInfo.tsx
  src/components/detail/SellerInfo.tsx
  src/components/error/ErrorETC.tsx
  src/components/modal/BuyerModal.tsx
  src/components/modal/KakaoModal.tsx
  src/components/mypage/member/MemberInfo.tsx
  src/components/mypage/member/Terms.tsx
  src/components/userProfile/Nav.tsx
  src/components/userProfile/ProfileBadge.tsx
  src/components/userProfile/UserComments.tsx
  src/components/userProfile/UserOnSale.tsx
  src/components/userProfile/UserPageProfile.tsx
  src/pages/CategoryPage.tsx
  src/pages/UserProfile.tsx
  src/pages/WritePage.tsx
  src/router/Router.tsx
  src/styles/styledComponent/detail.ts
  src/types.d.ts
Labels: enhancement

#171 Feat/user feedback 2
  src/components/categoryHome/Post.tsx
  src/components/etc/MoveTop.tsx
  src/components/home/Banner.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/modal/CustomModal.tsx
  src/components/modal/KakaoModal.tsx
  src/components/userProfile/Nav.tsx
  src/components/userProfile/UserPageProfile.tsx
  src/pages/Detail.tsx
  src/pages/Home.tsx
  src/pages/Transaction.tsx
  src/pages/UserProfile.tsx
  src/styles/GlobalStyle.tsx
  src/styles/styledComponent/auth.ts
  src/styles/styledComponent/category.ts
  src/styles/styledComponent/detail.ts
  src/styles/styledComponent/home.ts
Labels: enhancement

#172 Fix/search input
  src/components/etc/SearchInput.tsx
  src/pages/Home.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
Labels: bug

#173 Feat/user feedback 3
  package.json
  src/components/categoryHome/Post.tsx
  src/components/etc/SearchInput.tsx
  src/components/home/Banner.tsx
  src/components/layout/Header.tsx
  src/pages/Home.tsx
  src/styles/styledComponent/auth.ts
  src/styles/styledComponent/category.ts
  src/styles/styledComponent/detail.ts
  src/styles/styledComponent/home.ts
  src/styles/styledComponent/myPage.ts
  tsconfig.json
Labels: bug

#174 fix : 모달 크기 버그 수정, a태그 삭제 후 변경
  src/components/error/ErrorETC.tsx
  src/components/modal/CustomModal.tsx
  src/styles/styledComponent/home.ts
Labels: bug

#175 feat(Badge): '회원정보 변경'의 배지 로직에 의한 UI를 수정합니다.
  src/components/mypage/member/Badge.tsx
  src/components/mypage/member/ProfileImg.tsx
Labels: enhancement

#179 feat,fix,ui/detail,transaction:
  src/api.ts
  src/atom.ts
  src/components/comment/CommentsList.tsx
  src/components/detail/PostImg.tsx
  src/components/detail/PostInfo/NavBar.tsx
  src/components/detail/PostInfo/PostInfo.tsx
  src/components/detail/PostInfo/PostInfoStyle.ts
  src/components/detail/SellerInfo.tsx
  src/components/detail/content/Content.ts
  src/components/detail/content/DetailContent.tsx
  src/components/modal/BuyerModal.tsx
  src/components/transaction/PostInfo/PostInfo.tsx
  src/components/transaction/PostInfo/PostInfoStyle.ts
  src/components/transaction/content/Content.tsx
  src/pages/Detail.tsx
  src/pages/ReviewPage.tsx
  src/pages/Transaction.tsx
  src/styles/styledComponent/detail.ts
  src/types.d.ts
Labels: enhancement

#180 fix/detail,transaction: 머지 후 에러 수정
  src/components/comment/CommentsList.tsx
  src/components/detail/PostImg.tsx
  src/components/detail/PostInfo/PostInfo.tsx
  src/components/detail/SellerInfo.tsx
  src/components/detail/content/DetailContent.tsx
Labels: enhancement

#181 Feat/user feedback 6
  src/components/comment/CommentsList.tsx
  src/components/detail/BuyerInfo.tsx
  src/components/detail/PostInfo/PostInfo.tsx
  src/components/detail/SellerInfo.tsx
  src/components/detail/content/DetailContent.tsx
  src/components/etc/MoveTop.tsx
  src/components/modal/BuyerModal.tsx
  src/components/modal/CustomModal.tsx
  src/components/mypage/PointHistoryList.tsx
  src/components/transaction/PostInfo/PostInfo.tsx
  src/components/transaction/content/Content.tsx
  src/components/userProfile/Nav.tsx
  src/components/userProfile/UserComments.tsx
  src/components/userProfile/UserOnSale.tsx
  src/components/userProfile/UserPageProfile.tsx
  src/index.tsx
  src/pages/Detail.tsx
  src/pages/EditPage.tsx
  src/pages/MyPage.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/Transaction.tsx
  src/pages/WritePage.tsx
Labels: enhancement

#182 fix/mypage,detail,profilepage:
  src/components/detail/PostInfo/NavBar.tsx
  src/components/userProfile/UserOnSale.tsx
  src/pages/MyPage.tsx
Labels: bug, enhancement

#184 fix(mypage): 마이페이지의 기능을 수정합니다.
  src/api.ts
  src/components/mypage/PointHistoryList.tsx
  src/components/mypage/member/ProfileImg.tsx
  src/pages/MyPage.tsx
Labels: enhancement

#186 feat : 상세페이지 내 이미지 클릭 시 모달로 이미지 100% 띄우기
  src/components/detail/PostImg.tsx
  src/components/modal/KakaoModal.tsx
Labels: enhancement

#187 Fix/write
  src/pages/WritePage.tsx
Labels: bug

#188 Feat,UI/chat
  src/components/detail/BuyerInfo.tsx
  src/components/detail/PostInfo/PostInfo.tsx
  src/components/detail/PostInfo/PostInfoStyle.ts
  src/components/detail/SellerInfo.tsx
  src/components/detail/content/Content.ts
  src/components/modal/KakaoModal.tsx
  src/components/transaction/content/Content.tsx
  src/pages/Transaction.tsx
  src/types.d.ts
Labels: enhancement

#189 feat:채팅내에서 이미지를 보내는 기능 추가
  src/components/modal/KakaoModal.tsx
  src/types.d.ts
Labels: enhancement

#190 fix/buyermodal:
  src/atom.ts
  src/components/detail/PostInfo/PostInfo.tsx
  src/components/modal/BuyerModal.tsx
Labels: enhancement

#191 fix:채팅창에서 이미지 클릭시 크게 볼수있게 수정
  src/components/modal/BuyerModal.tsx
  src/components/modal/KakaoModal.tsx
Labels: enhancement

#192 Feat/user feedback 8
  public/index.html
  src/components/detail/PostInfo/PostInfo.tsx
  src/components/home/Banner.tsx
  src/index.tsx
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/styles/styledComponent/home.ts
Labels: enhancement

#193 fix/detail:
  src/atom.ts
  src/components/detail/PostInfo/PostInfo.tsx
  src/pages/MyPage.tsx
  src/pages/UserProfile.tsx
Labels: enhancement

#194 fix/etc: 자잘한 에러 수정
  src/atom.ts
  src/components/detail/PostInfo/PostInfo.tsx
  src/components/modal/BuyerModal.tsx
  src/components/modal/KakaoModal.tsx
  src/pages/Detail.tsx
  src/pages/MyPage.tsx
  src/pages/WritePage.tsx
Labels: enhancement

#195 Feat/user feedback 9
  src/components/categoryHome/Post.tsx
  src/components/detail/PostInfo/PostInfo.tsx
  src/components/home/Banner.tsx
  src/components/modal/BuyerModal.tsx
  src/components/modal/KakaoModal.tsx
  src/pages/EditPage.tsx
  src/pages/Home.tsx
  src/pages/WritePage.tsx
  src/styles/basicPost.webp
  src/styles/styledComponent/category.ts
Labels: enhancement

#196 feat(mypage): 고객 문의하기 기능을 만듭니다.
  src/api.ts
  src/components/etc/Inquire.tsx
  src/components/etc/inquire/AddForm.tsx
  src/components/etc/inquire/InquireList.tsx
  src/components/etc/inquire/InquirePost.tsx
Labels: enhancement

#197 feat(header): 판매중 Post 수를 나타냅니다.
  src/components/layout/Header.tsx
Labels: enhancement

#198 Feat/user feedback 10
  src/App.tsx
  src/atom.ts
  src/components/categoryHome/CategoryIntros.tsx
  src/components/comment/CommentInput.tsx
  src/components/detail/BuyerInfo.tsx
  src/components/detail/PostImg.tsx
  src/components/detail/PostInfo/PostInfo.tsx
  src/components/detail/SellerInfo.tsx
  src/components/detail/content/DetailContent.tsx
  src/components/etc/SearchInput.tsx
  src/components/layout/Header.tsx
  src/components/modal/KakaoModal.tsx
  src/components/mypage/PointHistoryList.tsx
  src/components/mypage/PointModal.tsx
  src/components/mypage/member/Badge.tsx
  src/components/mypage/member/MemberInfo.tsx
  src/components/mypage/member/ProfileImg.tsx
  src/components/transaction/PostInfo/PostInfo.tsx
  src/components/transaction/content/Content.tsx
  src/components/userProfile/Nav.tsx
  src/components/userProfile/ProfileBadge.tsx
  src/components/userProfile/UserComments.tsx
  src/components/userProfile/UserOnSale.tsx
  src/components/userProfile/UserPageProfile.tsx
  src/pages/CategoryPage.tsx
  src/pages/Detail.tsx
  src/pages/EditPage.tsx
  src/pages/MyPage.tsx
  src/pages/ReviewPage.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/Transaction.tsx
  src/router/Router.tsx
Labels: enhancement

#199 fix/mypage
  src/pages/MyPage.tsx
  src/styles/styledComponent/myPage.ts
Labels: enhancement

#200 Feat/home drop down
  README.md
  src/atom.ts
  src/components/detail/PostInfo/PostInfo.tsx
  src/components/layout/Header.tsx
  src/components/modal/HeaderbuyerModal.tsx
  src/pages/Detail.tsx
  src/pages/Home.tsx
Labels: enhancement

#201 Feat/user feedback 11
  README.md
  src/components/detail/PostInfo/PostInfo.tsx
  src/components/detail/PostInfo/PostInfoStyle.ts
  src/components/home/Banner.tsx
  src/components/layout/Header.tsx
  src/components/modal/BuyerModal.tsx
  src/components/modal/CustomModal.tsx
  src/components/modal/HeaderbuyerModal.tsx
  src/components/modal/KakaoModal.tsx
  src/pages/Home.tsx
  src/styles/styledComponent/category.ts
  src/styles/styledComponent/myPage.ts
Labels: enhancement

#202 Feat/user feedback 12
  src/pages/Home.tsx
  src/styles/styledComponent/home.ts
Labels: enhancement

#203 Fix/sellerinfo
  src/components/detail/SellerInfo.tsx
  src/components/userProfile/ProfileBadge.tsx
Labels: enhancement

#204 fix(mypage):포인트내역에 상대 닉네임이 보입니다. 닉네임 중복 검사 로직을 수정합니다.
  src/atom.ts
  src/components/mypage/PointHistoryList.tsx
  src/components/mypage/member/MemberInfo.tsx
  src/components/mypage/member/UserName.tsx
  src/pages/MyPage.tsx
  src/styles/styledComponent/myPage.ts
Labels: enhancement

#205 fix(UserName): 닉네임 중복검사 로직을 심화 합니다.
  src/components/mypage/member/MemberInfo.tsx
  src/components/mypage/member/UserName.tsx
Labels: bug

#206 feat : refactory-part2
  README.md
  public/index.html
  src/api.ts
  src/components/auth/FindPW.tsx
  src/components/categoryHome/CategoryIntros.tsx
  src/components/categoryHome/Post.tsx
  src/components/comment/CommentInput.tsx
  src/components/detail/PostImg.tsx
  src/components/detail/PostInfo/NavBar.tsx
  src/components/detail/PostInfo/PostInfo.tsx
  src/components/detail/SellerInfo.tsx
  src/components/etc/Inquire.tsx
  src/components/etc/Loader.tsx
  src/components/etc/inquire/AddForm.tsx
  src/components/etc/inquire/InquireList.tsx
  src/components/etc/inquire/InquirePost.tsx
  src/components/home/Banner.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/modal/BuyerModal.tsx
  src/components/modal/HeaderbuyerModal.tsx
  src/components/modal/KakaoModal.tsx
  src/components/mypage/PointHistoryList.tsx
  src/components/mypage/PointModal.tsx
  src/components/mypage/member/Badge.tsx
  src/components/mypage/member/MemberInfo.tsx
  src/components/mypage/member/ProfileImg.tsx
  src/components/mypage/member/UserName.tsx
  src/components/transaction/PostInfo/PostInfo.tsx
  src/components/transaction/content/Content.tsx
  src/components/userProfile/Nav.tsx
  src/components/userProfile/ProfileBadge.tsx
  src/components/userProfile/UserComments.tsx
  src/components/userProfile/UserOnSale.tsx
  src/components/userProfile/UserPageProfile.tsx
  src/pages/CategoryPage.tsx
  src/pages/Detail.tsx
  src/pages/EditPage.tsx
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/pages/ReviewPage.tsx
  src/pages/SignUp.tsx
  src/pages/Transaction.tsx
  src/pages/UserProfile.tsx
  src/pages/WritePage.tsx
  src/styles/styledComponent/myPage.ts
  src/styles/styledComponent/writeEdit.ts
Labels: enhancement

#211 hotfix : 글쓰기 페이지 로딩 loading
  src/pages/WritePage.tsx
Labels: enhancement

#212 hotfix : 거래 취소 버그 수정
  src/api.ts
Labels: bug

#213 hotfix : favico변경 및 기본 이미지 변경
  public/assets/basicIMG.jpg
  public/assets/basicIMG.webp
  public/favicon.ico
  src/pages/Home.tsx
  src/pages/MyPage.tsx
Labels: bug

#214 hotfix : home data 에러
  src/components/detail/SellerInfo.tsx
  src/pages/Home.tsx
Labels: bug

#215 hotfix
  src/pages/EditPage.tsx
Labels: bug

#216 hotfix : header와 구매완료 시 confirm으로 변경
  src/components/layout/Header.tsx
  src/components/transaction/PostInfo/PostInfo.tsx
Labels: bug

#217 hotfix : 용어 변경
  src/components/layout/Header.tsx
  src/pages/Transaction.tsx
Labels: bug

#218 hotfix : bug 에러 수정
  src/components/layout/Header.tsx
  src/components/modal/BuyerModal.tsx
  src/components/modal/HeaderbuyerModal.tsx
  src/components/transaction/OnSalePostImg .tsx
  src/pages/Transaction.tsx
Labels: bug

#219 hotfix : 탈퇴 bug수정
  src/pages/MyPage.tsx
Labels: bug

#220 hotfix : loader추가하기
  src/pages/Transaction.tsx
Labels: bug

#222 feat : seo-setUp
  package.json
  public/assets/basicIMG.jpg
  public/assets/basicIMG.webp
  public/favicon.ico
  public/index.html
  src/App.tsx
  src/api.ts
  src/components/detail/SellerInfo.tsx
  src/components/layout/Header.tsx
  src/components/modal/BuyerModal.tsx
  src/components/modal/HeaderbuyerModal.tsx
  src/components/mypage/PointModal.tsx
  src/components/mypage/member/MemberInfo.tsx
  src/components/transaction/OnSalePostImg .tsx
  src/components/transaction/PostInfo/PostInfo.tsx
  src/index.tsx
  src/pages/EditPage.tsx
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/pages/Transaction.tsx
  src/pages/UserProfile.tsx
  src/pages/WritePage.tsx
Labels: enhancement

#224 hotfix : profile-img
  README.md
  src/components/mypage/member/ProfileImg.tsx
Labels: bug

#225 feat : seo세팅
  package.json
  src/App.tsx
  src/index.tsx
Labels: enhancement

#226 Feat/first clean code
  README.md
  package.json
  src/App.tsx
  src/components/mypage/member/ProfileImg.tsx
  src/index.tsx
  src/pages/CategoryPage.tsx
  src/pages/Detail.tsx
  src/pages/EditPage.tsx
  src/pages/MyPage.tsx
  src/pages/ReviewPage.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/Transaction.tsx
  src/pages/UserProfile.tsx
  src/pages/WritePage.tsx
Labels: duplicate, enhancement

#227 Fix/auth
  README.md
  src/components/auth/FindPW.tsx
  src/components/transaction/OnSalePostImg.tsx
  src/pages/MyPage.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/Transaction.tsx
Labels: enhancement

#228 fix/Header: 창이 작아지면 UI가 겹치게 되는 부분 수정
  src/components/layout/Header.tsx
  src/pages/SignIn.tsx
Labels: enhancement
